export const validExercises = [
  // Chest
  "Push-up",
  "Incline Push-up",
  "Decline Push-up",
  "Bench Press",
  "Barbell Bench Press",
  "Dumbbell Bench Press",
  "Incline Bench Press",
  "Incline Dumbbell Press",
  "Incline Barbell Press",
  "Decline Bench Press",
  "Chest Fly",
  "Dumbbell Fly",
  "Cable Fly",
  "Incline Cable Fly",
  "Pec Deck Fly",
  "Chest Press",
  "Machine Chest Press",
  "Cable Crossover",
  "Dips",
  "Chest Dips",
  "Dumbbell Pullover",
  "EZ Bar Pullover",
  "Barbell Pullover",

  // Back
  "Lat Pulldown",
  "Wide-Grip Lat Pulldown",
  "Close-Grip Lat Pulldown",
  "Reverse Grip Lat Pulldown",
  "Pull-up",
  "Chin-up",
  "Seated Cable Row",
  "Cable Row",
  "Bent-over Row",
  "Barbell Row",
  "Bent-Over Barbell Row",
  "Reverse-Grip Bent-Over Row",
  "EZ Bar Row",
  "Bent-Over EZ Bar Row",
  "Reverse-Grip Bent-Over EZ Bar Row",
  "Underhand EZ Bar Bent-Over Row",
  "Dumbbell Row",
  "Single-Arm Dumbbell Row",
  "T-Bar Row",
  "Chest-Supported Row",
  "Meadows Row",
  "Pendlay Row",
  "Straight-Arm Pulldown",
  "Face Pull",
  "Deadlift",
  "Conventional Deadlift",
  "Sumo Deadlift",
  "Romanian Deadlift",
  "Dumbbell Romanian Deadlift",
  "Barbell Romanian Deadlift",
  "Single-Leg Romanian Deadlift",
  "Good Mornings",
  "Back Extension",
  "Hyperextension",

  // Shoulders
  "Shoulder Press",
  "Overhead Press",
  "Barbell Shoulder Press",
  "Dumbbell Shoulder Press",
  "Military Press",
  "Arnold Press",
  "Seated Dumbbell Press",
  "Smith Machine Shoulder Press",
  "Machine Shoulder Press",
  "Lateral Raise",
  "Dumbbell Lateral Raise",
  "Cable Lateral Raise",
  "Machine Lateral Raise",
  "Front Raise",
  "Dumbbell Front Raise",
  "Barbell Front Raise",
  "Plate Front Raise",
  "Rear Delt Fly",
  "Reverse Pec Deck",
  "Dumbbell Rear Delt Fly",
  "Cable Rear Delt Fly",
  "Upright Row",
  "Barbell Upright Row",
  "Cable Upright Row",
  "EZ Bar Upright Row",
  "Shrugs",
  "Dumbbell Shrugs",
  "Barbell Shrugs",
  "Landmine Press",

  // Arms - Biceps & Triceps & Forearms
  "Bicep Curl",
  "Barbell Curl",
  "Dumbbell Curl",
  "EZ Bar Curl",
  "Hammer Curl",
  "Dumbbell Hammer Curl",
  "Cable Hammer Curl",
  "Preacher Curl",
  "EZ Bar Preacher Curl",
  "Dumbbell Preacher Curl",
  "Incline Dumbbell Curl",
  "Concentration Curl",
  "Cable Curl",
  "Spider Curl",
  "Reverse Curl",
  "Tricep Pushdown",
  "Cable Tricep Pushdown",
  "Rope Tricep Pushdown",
  "Tricep Extension",
  "Overhead Tricep Extension",
  "Dumbbell Overhead Tricep Extension",
  "Cable Overhead Tricep Extension",
  "EZ Bar Skullcrushers",
  "Skullcrushers",
  "Lying Tricep Extension",
  "Close-Grip Bench Press",
  "Tricep Dips",
  "Bench Dips",
  "Tricep Kickback",
  "Dumbbell Kickback",

  // Legs & Lower Body
  "Back Squat",
  "Barbell Back Squat",
  "Front Squat",
  "Barbell Front Squat",
  "Goblet Squat",
  "Dumbbell Goblet Squat",
  "Kettlebell Goblet Squat",
  "Bulgarian Split Squat",
  "Dumbbell Bulgarian Split Squat",
  "Leg Press",
  "Hack Squat",
  "Machine Hack Squat",
  "Smith Machine Squat",
  "Lunges",
  "Walking Lunges",
  "Reverse Lunges",
  "Dumbbell Lunges",
  "Step-ups",
  "Dumbbell Step-ups",
  "Leg Extension",
  "Leg Curl",
  "Lying Leg Curl",
  "Seated Leg Curl",
  "Hip Thrust",
  "Barbell Hip Thrust",
  "Dumbbell Hip Thrust",
  "Glute Bridge",
  "Calf Raise",
  "Standing Calf Raise",
  "Seated Calf Raise",
  "Donkey Calf Raise",

  // Core & Abs
  "Plank",
  "Side Plank",
  "Mountain Climbers",
  "Crunches",
  "Cable Crunch",
  "Leg Raise",
  "Hanging Leg Raise",
  "Hanging Knee Raise",
  "Ab Wheel Rollout",
  "Russian Twist",
  "Bicycle Crunches"
];