export const validExercises = [
  "Push-up",
  "Incline Push-up",
  "Bench Press",
  "Incline Bench Press",
  "Chest Fly",
  "Lat Pulldown",
  "Pull-up",
  "Seated Cable Row",
  "Bent-over Row",
  "Deadlift",
  "Romanian Deadlift",
  "Back Squat",
  "Front Squat",
  "Goblet Squat",
  "Bulgarian Split Squat",
  "Leg Press",
  "Shoulder Press",
  "Lateral Raise",
  "Bicep Curl",
  "Hammer Curl",
  "Tricep Pushdown",
  "Dips",
  "Plank",
  "Mountain Climbers"
];